main: coathar.trivia.triviabot.Main
name: TriviaBot
version: 1.0
author: Coathar
description: A bot to make trivia questions
commands:
  triviastart:
    description: Starts the bot for a question
    usage: /triviastart
    permisison: triviabot.start
    permission-message: You do not have permission to do that!
  triviatoggleloop:
    description: toggles looping of questions. Will start trivia if the loop is toggled to on and trivia has not started.
    usage: /toggletrivialoop
    permission: triviabot.start
    permission-message: You do not have permission to do that!
  triviareload:
    description: Reloads the trivia config
    usage: /triviareload
    permission: triviabot.reload
    permission-message: You do not have permission to do that!